### PR TITLE
Check for object instead of string

### PR DESCRIPTION
**Pull request by i-am-the-slime**
I'm not 💯 on why there is this check is there (is it meant to be the opposite?) but I lose my data props with it.

### CODE REVIEW

**Comment by hdgarrood** [comment]
That does seem a little bit odd. The `flattenDataProp` function isn't using its `component` argument otherwise, and `flattenDataProp` is only used from inside `element_`, in which case `component` should be a `ReactComponent`, and that could have a few different runtime representations but as far as I know a String isn't one of them.

**Comment by maddie927** [comment]
`_data` props are only meant to be used on DOM elements, which are strings: `React.createElement("div", props, children)`. `unsafeCreateDOMComponent` promotes a `String` to a `ReactComponent`.

**Comment by hdgarrood** [comment]
I might be missing something but from my reading of [the source](https://github.com/lumihq/purescript-react-basic-dom/blob/cb761db2ea6722c793f74757333893ff558a7bf0/src/React/Basic/DOM/Internal.js#L8), the result of unsafeCreateDOMComponent won’t ever be a string

**Comment by i-am-the-slime** [comment]
I'm also still confused. When I do:

```js
  console.log(React.createElement("div", { "data-x": "1"}))
```

I get this: 
```js
{type: "div", key: null, ref: null, props: Object, _owner: FiberNode…}
```

With a `typeof` in front I get: `object`.

Or do you mean that `"div"` before doing the `createElement` is a string? But then it won't have props yet, right?

**Comment by maddie927** [comment]
```js
{type: "div", key: null, ref: null, props: Object, _owner: FiberNode…}
```

This is "compiled" JSX and internal to React, so we try to avoid messing with it at this point. You should find your `data-x` prop inside the `Object` assigned to `props`, though.

---

The old version of `unsafeCreateDOMComponent` was `unsafeCoerce :: String -> ReactComponent props`. This was back when the DOM modules and `React.Basic.element` were in the same `react-basic` library. Once the DOM modules were moved to their own library, it seemed odd to keep this `data-*` flattening behavior in `React.Basic.element`, because this behavior is really specific to the DOM elements (it's not `React.createElement` that understands "data props should work if the component is the string `"div"`", it's `ReactDOM.render` which processes the "compiled" JSX objects mentioned above). `react-native` doesn't have this behavior, and it also doesn't make sense on custom components but the `typeof component === "string"` handles that.

Anyway the current version of `React.Basic.element` removes this behavior and it instead comes from [this wrapper component](https://github.com/lumihq/purescript-react-basic-dom/blob/cb761db2ea6722c793f74757333893ff558a7bf0/src/React/Basic/DOM/Internal.js#L8) @hdgarrood mentioned above. That means this emotion-specific version -- a slightly modified copy of the old `React.Basic.element` -- is slightly out of date and this code shouldn't ever run. I don't think it hurts to leave it though, in case it's being used with an old version of `react-basic`.

@i-am-the-slime, what's the actual problem you're seeing? Are you rendering DOM elements or something else?

**Comment by i-am-the-slime** [comment]
@spicydonuts 
Thank you very much for explaining this in more detail, I am very grateful for this! I finally understand it now :). I tried to reproduce my problem but was unable to.
I'm suspecting I was doing some "forwardRef" things wrong previously or maybe pointing to incompatible versions of this library and another one in their family. 
I'll close this for now but if I can reproduce it I'll come back here and report!

**Comment by i-am-the-slime** [comment]
I have found it again and do remember :)

I have some bindings to `framer-motion`. They expose essentially all basic `DOM` and `SVG` "stringy" components as their own `motion` variants. I modelled these as taking a superset of props to their react-basic counterparts. Now these aren't strings, but I'd still like to be able to pass aria and data props to them. I suppose I could probably create a separate `element` function for these motion components. The change I proposed in this PR was an easier fix.
I'm also curious to hear how you would model such components.

**Comment by maddie927** [comment]
Ah, I see. I would probably build the library with a dependency on `react-basic-dom`, using the existing element types extended with `framer-motion` props, then in the FFI file define a wrapper similar to the one in `react-basic-dom` and use it to define each component. Something like this:

```purs
type Props_div = ( animationStuff :: * | DOM.Props_div )

foreign import div
  :: forall attrs attrs_
   . Union attrs attrs_ Props_div
  => Record attrs
  -> JSX
```

```js
const div = dataAriaFlatteningWrapper(motion.div)
exports.div = _unionDict => div
```

**Pull request closed without merging**
